package com.emailextractor.controller;

import com.emailextractor.model.FileTemplate;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 * Created by supra on 9/17/2017.
 */
public class FileFinder {

    private String path;

    public FileFinder(String path){
        this.path = path;
    }

    public FileFinder(){
        this.path = ".";
    }

    public String[] getFileList(){

        File folder = new File(this.path);
        File[] listOfFiles = folder.listFiles();
        String[] listOfFilesName = new String[listOfFiles.length];

        for (int i =0; i < listOfFiles.length; ++i){
            listOfFilesName[i] = listOfFiles[i].getName();
        }

        return listOfFilesName;
    }

    public String[] extractEmailFromListOfFiles(String[] fileNameList){
        String fileContent, manual = "";
        String[] emailList = new String[fileNameList.length];

        for (int i =0; i<fileNameList.length;++i){
            try {
                fileContent = new String(Files.readAllBytes(Paths.get(this.path + "/" + fileNameList[i])));
                switch (FileTemplate.getSenderType(fileContent)){
                    case FileTemplate.ANONYMOUS :
                        manual += fileNameList[i] + ", ";
                        break;
                    case FileTemplate.AUTOGENERATED :
                        
                }

                //emailList[i] = fileContent;
            } catch (Exception e){
                System.out.println("cannot find file exception! contact supratik");
            }
        }

        return emailList;
    }
}
