package com.emailextractor.model;

import java.util.regex.Pattern;

/**
 * Created by supra on 9/17/2017.
 */
public class FileTemplate {
    public static final String detectAutoGeneratedMailRegex = "subject: No Reply";
    public static final String detectShopkeeperManualMailRegex = "subject: Shopkeeper";
    public static final String uniqueIdMailRegex = "id: \\d+{4}";
    public static final String shopkeeperMailIdRegex = "[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?";

    public static final int SHOPKEEPER = 1;
    public static final int AUTOGENERATED = 2;
    public static final int ANONYMOUS = 0;

    public static int getSenderType(String content) {
        if (Pattern.matches(FileTemplate.detectAutoGeneratedMailRegex, content)) {
            return FileTemplate.AUTOGENERATED;
        } else if(Pattern.matches(FileTemplate.detectShopkeeperManualMailRegex,content)){
            return FileTemplate.SHOPKEEPER;
        }
        return FileTemplate.ANONYMOUS;
    }
}
